## Welcome to bytebazzar analysis

In [2]:
import pandas as pd

raw_data = pd.read_csv('ecommerce_orders.csv')
df = raw_data

In [3]:
df.head()

,OrderLineID,OrderID,OrderDate,CustomerName,City,ProductName,Category,Quantity,UnitPrice_BDT,PaymentMethod,OrderStatus,InternalNote
0,1001,ORD-5001,2026-09-02,Imran Hossain,Dhaka,Laptop Stand,Accessories,3,1650,bKash,Shipped,Call before delivery
1,1002,ORD-5001,2026-09-28,Tanvir Ahmed,Chattogram,Notebook Pack,Stationery,1,300,Bank Transfer,Returned,—
2,1003,ORD-5002,2026-10-16,Nabil Chowdhury,Cumilla,27-inch Monitor,Electronics,2,24500,Cash on Delivery,Shipped,Call before delivery
3,1004,ORD-5002,2026-10-19,Maliha Islam,Rajshahi,Wireless Mouse,Accessories,3,850,Card,Pending,Gift wrap
4,1005,ORD-5003,2026-09-07,Sabbir Hossain,Khulna,Webcam,Electronics,1,3800,Card,Returned,—

In [4]:
df.tail()

,OrderLineID,OrderID,OrderDate,CustomerName,City,ProductName,Category,Quantity,UnitPrice_BDT,PaymentMethod,OrderStatus,InternalNote
55,1056,ORD-5019,2026-09-22,Imran Hossain,Dhaka,Office Chair,Home Office,4,13100,Bank Transfer,Shipped,Promo campaign
56,1057,ORD-5029,2026-10-09,Ayesha Rahman,Dhaka,Laptop Stand,Accessories,1,1650,Cash on Delivery,Pending,Call before delivery
57,1058,ORD-5029,2026-09-25,Nabil Chowdhury,Cumilla,Laptop Stand,Accessories,4,1650,Cash on Delivery,Delivered,—
58,1059,ORD-5030,2026-10-14,Nabil Chowdhury,Cumilla,Office Chair,Home Office,2,12500,Card,Shipped,Repeat customer
59,1060,ORD-5030,2026-10-10,Tanvir Ahmed,Chattogram,Webcam,Electronics,1,3600,Bank Transfer,Pending,Promo campaign

In [5]:
df.sample(10)

,OrderLineID,OrderID,OrderDate,CustomerName,City,ProductName,Category,Quantity,UnitPrice_BDT,PaymentMethod,OrderStatus,InternalNote
40,1041,ORD-5014,2026-09-30,Nusrat Jahan,Dhaka,USB Flash Drive 64GB,Storage,1,850,bKash,Delivered,Repeat customer
13,1014,ORD-5007,2026-09-26,Shakib Rahman,Chattogram,Notebook Pack,Stationery,1,350,Bank Transfer,Shipped,Repeat customer
46,1047,ORD-5024,2026-09-03,Oishee Karim,Khulna,SSD 1TB,Storage,1,9800,Nagad,Pending,Repeat customer
14,1015,ORD-5008,2026-10-26,Tanvir Ahmed,Chattogram,Mechanical Keyboard,Accessories,1,3200,Bank Transfer,Cancelled,—
11,1012,ORD-5006,2026-10-07,Tanvir Ahmed,Chattogram,27-inch Monitor,Electronics,3,24500,Cash on Delivery,Cancelled,Repeat customer
44,1045,ORD-5023,2026-10-18,Tanvir Ahmed,Chattogram,Laptop Stand,Accessories,2,1650,Nagad,Returned,Promo campaign
0,1001,ORD-5001,2026-09-02,Imran Hossain,Dhaka,Laptop Stand,Accessories,3,1650,bKash,Shipped,Call before delivery
35,1036,ORD-5012,2026-09-14,Sabbir Hossain,dhaka,USB Flash Drive 64GB,Storage,5,850,bKash,Returned,Promo campaign
32,1033,ORD-5017,2026-09-06,Oishee Karim,Khulna,Wireless Mouse,Accessories,4,850,Cash on Delivery,Shipped,Repeat customer
48,1049,ORD-5025,2026-10-08,Oishee Karim,Khulna,Laptop,Computers,2,78500,Card,Delivered,Promo campaign

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderLineID    60 non-null     int64
 1   OrderID        60 non-null     str
 2   OrderDate      60 non-null     str
 3   CustomerName   60 non-null     str
 4   City           60 non-null     str
 5   ProductName    60 non-null     str
 6   Category       60 non-null     str
 7   Quantity       60 non-null     int64
 8   UnitPrice_BDT  60 non-null     int64
 9   PaymentMethod  60 non-null     str
 10  OrderStatus    60 non-null     str
 11  InternalNote   60 non-null     str
dtypes: int64(3), str(9)
memory usage: 5.8 KB

In [7]:
df.describe()

       OrderLineID  Quantity  UnitPrice_BDT
count    60.000000  60.00000      60.000000
mean   1030.500000   1.90000   11025.000000
std      17.464249   1.16007   18757.835651
min    1001.000000   1.00000     300.000000
25%    1015.750000   1.00000    1350.000000
50%    1030.500000   1.00000    3200.000000
75%    1045.250000   3.00000   10475.000000
max    1060.000000   5.00000   78500.000000

In [8]:
df['ProductName'].unique()

<StringArray>
[        'Laptop Stand',        'Notebook Pack',      '27-inch Monitor',
       'Wireless Mouse',               'Webcam',        'Phone Charger',
     'Wireless Earbuds', 'USB Flash Drive 64GB',               'Laptop',
     'Portable Speaker',              'SSD 1TB',  'Mechanical Keyboard',
               'Tablet',         'Office Chair',           'Power Bank',
            'Desk Lamp',      'Wireless Router', 'Bluetooth Headphones',
           'Smartphone',            'USB-C Hub']
Length: 20, dtype: str

In [9]:
df.loc[3]

OrderLineID                1004
OrderID                ORD-5002
OrderDate            2026-10-19
CustomerName       Maliha Islam
City                   Rajshahi
ProductName      Wireless Mouse
Category            Accessories
Quantity                      3
UnitPrice_BDT               850
PaymentMethod              Card
OrderStatus             Pending
InternalNote          Gift wrap
Name: 3, dtype: object

In [10]:
df.rename(columns={'OrderStatus': 'Order Status'}, inplace=True)
df.drop('InternalNote', axis=1, inplace = True)

df.head()

C:\Users\Nazmul Hasan\AppData\Local\Temp\ipykernel_29496\2307393109.py:1: Pandas4Warning: The inplace keyword in DataFrame.rename is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  df.rename(columns={'OrderStatus': 'Order Status'}, inplace=True)
C:\Users\Nazmul Hasan\AppData\Local\Temp\ipykernel_29496\2307393109.py:2: Pandas4Warning: The inplace keyword in DataFrame.drop is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  df.drop('InternalNote', axis=1, inplace = True)

,OrderLineID,OrderID,OrderDate,CustomerName,City,ProductName,Category,Quantity,UnitPrice_BDT,PaymentMethod,Order Status
0,1001,ORD-5001,2026-09-02,Imran Hossain,Dhaka,Laptop Stand,Accessories,3,1650,bKash,Shipped
1,1002,ORD-5001,2026-09-28,Tanvir Ahmed,Chattogram,Notebook Pack,Stationery,1,300,Bank Transfer,Returned
2,1003,ORD-5002,2026-10-16,Nabil Chowdhury,Cumilla,27-inch Monitor,Electronics,2,24500,Cash on Delivery,Shipped
3,1004,ORD-5002,2026-10-19,Maliha Islam,Rajshahi,Wireless Mouse,Accessories,3,850,Card,Pending
4,1005,ORD-5003,2026-09-07,Sabbir Hossain,Khulna,Webcam,Electronics,1,3800,Card,Returned

In [11]:
# removing the fist return row

df.drop(1, inplace=True)
df.head()

C:\Users\Nazmul Hasan\AppData\Local\Temp\ipykernel_29496\2160033910.py:3: Pandas4Warning: The inplace keyword in DataFrame.drop is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  df.drop(1, inplace=True)

,OrderLineID,OrderID,OrderDate,CustomerName,City,ProductName,Category,Quantity,UnitPrice_BDT,PaymentMethod,Order Status
0,1001,ORD-5001,2026-09-02,Imran Hossain,Dhaka,Laptop Stand,Accessories,3,1650,bKash,Shipped
2,1003,ORD-5002,2026-10-16,Nabil Chowdhury,Cumilla,27-inch Monitor,Electronics,2,24500,Cash on Delivery,Shipped
3,1004,ORD-5002,2026-10-19,Maliha Islam,Rajshahi,Wireless Mouse,Accessories,3,850,Card,Pending
4,1005,ORD-5003,2026-09-07,Sabbir Hossain,Khulna,Webcam,Electronics,1,3800,Card,Returned
5,1006,ORD-5002,2026-10-05,Mehjabin Noor,Rangpur,Phone Charger,Mobile,1,1250,Bank Transfer,Delivered

In [12]:
df.info()

<class 'pandas.DataFrame'>
Index: 59 entries, 0 to 59
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   OrderLineID    59 non-null     int64
 1   OrderID        59 non-null     str
 2   OrderDate      59 non-null     str
 3   CustomerName   59 non-null     str
 4   City           59 non-null     str
 5   ProductName    59 non-null     str
 6   Category       59 non-null     str
 7   Quantity       59 non-null     int64
 8   UnitPrice_BDT  59 non-null     int64
 9   PaymentMethod  59 non-null     str
 10  Order Status   59 non-null     str
dtypes: int64(3), str(8)
memory usage: 5.5 KB

In [19]:
cheapest_5 = df.nsmallest(5, 'UnitPrice_BDT')
cheapest_5

,OrderLineID,OrderID,OrderDate,CustomerName,City,ProductName,Category,Quantity,UnitPrice_BDT,PaymentMethod,Order Status
38,1039,ORD-5020,2026-09-16,Shakib Rahman,Chattogram,Notebook Pack,Stationery,2,300,Bank Transfer,Cancelled
13,1014,ORD-5007,2026-09-26,Shakib Rahman,Chattogram,Notebook Pack,Stationery,1,350,Bank Transfer,Shipped
41,1042,ORD-5021,2026-09-07,Tania Sultana,Barishal,Notebook Pack,Stationery,1,350,Nagad,Pending
21,1022,ORD-5011,2026-09-06,Sabbir Hossain,Khulna,Notebook Pack,Stationery,1,350,Bank Transfer,Delivered
32,1033,ORD-5017,2026-09-06,Oishee Karim,Khulna,Wireless Mouse,Accessories,4,850,Cash on Delivery,Shipped

sorting by Category descending and UnitPrice_BDT ascending.

In [21]:
df.sort_values(['Category', 'UnitPrice_BDT'], ascending=[0,1], inplace=True)
df.head()

C:\Users\Nazmul Hasan\AppData\Local\Temp\ipykernel_29496\1059421290.py:1: Pandas4Warning: The inplace keyword in DataFrame.sort_values is deprecated and will be removed in a future version (PDEP-8).
See https://pandas.pydata.org/docs/dev/whatsnew/v3.1.0.html#deprecation-inplace for more details.
  df.sort_values(['Category', 'UnitPrice_BDT'], ascending=[0,1], inplace=True)

,OrderLineID,OrderID,OrderDate,CustomerName,City,ProductName,Category,Quantity,UnitPrice_BDT,PaymentMethod,Order Status
40,1041,ORD-5014,2026-09-30,Nusrat Jahan,Dhaka,USB Flash Drive 64GB,Storage,1,850,bKash,Delivered
7,1008,ORD-5004,2026-09-06,Rakib Hasan,Mymensingh,USB Flash Drive 64GB,Storage,3,850,Card,Cancelled
35,1036,ORD-5012,2026-09-14,Sabbir Hossain,dhaka,USB Flash Drive 64GB,Storage,5,850,bKash,Returned
53,1054,ORD-5027,2026-10-23,Rafi Hasan,Dhaka,USB Flash Drive 64GB,Storage,3,850,Nagad,Delivered
12,1013,ORD-5007,2026-09-09,Nusrat Jahan,Dhaka,SSD 1TB,Storage,1,9800,Bank Transfer,Pending

### filtering data

In [29]:
delivered = df.loc[df['Order Status'] == 'Delivered']
delivered.iloc[:,[3,4,5,8,10]]

,CustomerName,City,ProductName,UnitPrice_BDT,Order Status
40,Nusrat Jahan,Dhaka,USB Flash Drive 64GB,850,Delivered
53,Rafi Hasan,Dhaka,USB Flash Drive 64GB,850,Delivered
45,Sabbir Hossain,Khulna,SSD 1TB,9800,Delivered
21,Sabbir Hossain,Khulna,Notebook Pack,350,Delivered
5,Mehjabin Noor,Rangpur,Phone Charger,1250,Delivered
31,Maliha Islam,Rajshahi,Phone Charger,1400,Delivered
43,Tania Sultana,Barishal,Desk Lamp,1350,Delivered
16,Imran Hossain,Dhaka,Office Chair,12500,Delivered
25,Nabil Chowdhury,Cumilla,Wireless Router,4600,Delivered
33,Sumaiya Akter,Chattogram,27-inch Monitor,25700,Delivered
48,Oishee Karim,Khulna,Laptop,78500,Delivered
6,Oishee Karim,Khulna,Wireless Earbuds,5600,Delivered
57,Nabil Chowdhury,Cumilla,Laptop Stand,1650,Delivered
29,Sumaiya Akter,Chattogram,Mechanical Keyboard,3200,Delivered
49,Shakib Rahman,Chattogram,Mechanical Keyboard,3200,Delivered

In [33]:
cancelled = df.loc[df['Order Status'] == 'Cancelled']
cancelled.iloc[:,[3,4,5,8,10]]

,CustomerName,City,ProductName,UnitPrice_BDT,Order Status
7,Rakib Hasan,Mymensingh,USB Flash Drive 64GB,850,Cancelled
38,Shakib Rahman,Chattogram,Notebook Pack,300,Cancelled
51,Shakib Rahman,Chattogram,Smartphone,36500,Cancelled
11,Tanvir Ahmed,Chattogram,27-inch Monitor,24500,Cancelled
9,Imran Hossain,Dhaka,Portable Speaker,2850,Cancelled
27,Nabil Chowdhury,Cumilla,Bluetooth Headphones,4200,Cancelled
42,Shakib Rahman,Chattogram,USB-C Hub,2450,Cancelled
14,Tanvir Ahmed,Chattogram,Mechanical Keyboard,3200,Cancelled

In [37]:
# unit price in at least 10000

at_least_10_k = df.loc[df['UnitPrice_BDT'] >= 10000]
at_least_10_k.iloc[:,[5,8]]

        ProductName  UnitPrice_BDT
50       Smartphone          36500
51       Smartphone          36500
28       Smartphone          36500
47       Smartphone          40150
58     Office Chair          12500
16     Office Chair          12500
23     Office Chair          12500
55     Office Chair          13100
11  27-inch Monitor          24500
2   27-inch Monitor          24500
33  27-inch Monitor          25700
15           Tablet          28900
19           Laptop          78500
8            Laptop          78500
48           Laptop          78500

In [43]:
pending_or_cancelled = df.loc[(df['Order Status'] == 'Pending') | (df['Order Status'] == 'Cancelled')]
pending_or_cancelled.count()

OrderLineID      22
OrderID          22
OrderDate        22
CustomerName     22
City             22
ProductName      22
Category         22
Quantity         22
UnitPrice_BDT    22
PaymentMethod    22
Order Status     22
dtype: int64

In [50]:
df.loc[(df['Category'] == 'Electronics') & (df['UnitPrice_BDT'] > 10000)]

,OrderLineID,OrderID,OrderDate,CustomerName,City,ProductName,Category,Quantity,UnitPrice_BDT,PaymentMethod,Order Status
11,1012,ORD-5006,2026-10-07,Tanvir Ahmed,Chattogram,27-inch Monitor,Electronics,3,24500,Cash on Delivery,Cancelled
2,1003,ORD-5002,2026-10-16,Nabil Chowdhury,Cumilla,27-inch Monitor,Electronics,2,24500,Cash on Delivery,Shipped
33,1034,ORD-5017,2026-10-26,Sumaiya Akter,Chattogram,27-inch Monitor,Electronics,1,25700,Cash on Delivery,Delivered